# RexChat Configuration

# Message Settings
messages:
  prefix: "&7[&#f75634RexChat&7] "
  no-permission: "%rc_prefix%&fYou don't have permission to use this command."
  reload-success: "%rc_prefix%&fConfiguration reloaded successfully!"
  command-not-found: "%rc_prefix%&fCommand not found."
  reload-usage: "%rc_prefix%&fUsage: /%cmd% reload"
  player-only: "%rc_prefix%&fThis command can only be used by players!"

# Chat Management Settings
chat-management:
  mute:
    permission: "rexchat.mute"
    muted-message: "%rc_prefix%&fThe chat is currently muted."
    mute-announcement: "%rc_prefix%&fThe chat has been muted by {player}"
    unmute-announcement: "%rc_prefix%&fThe chat has been unmuted by {player}"
  clear:
    permission: "rexchat.clear"
    clear-message: "%rc_prefix%&fThe chat has been cleared by {player}"
    lines: 100

# Commands Configuration
commands:
  discord:
    enabled: true
    command: "discord"
    aliases: ["dc"]
    permission: ""
    message-list:
      - "%rc_prefix%&#5865f2Discord Server"
      - "&7• &fJoin our community: &#00aaffhttps://discord.gg/yourserver"
      - "&7• &fOnline Members: &#00ff001,234+"

  rules:
    enabled: true
    command: "rules"
    aliases: ["rule"]
    permission: ""
    message-list:
      - "%rc_prefix%&#ff5555Server Rules"
      - "&7• &fBe respectful to all players"
      - "&7• &fNo spamming or excessive caps"
      - "&7• &fNo advertising or self-promotion"
      - "&7• &fNo griefing or stealing"
      - "&7• &fUse appropriate language"

  store:
    enabled: true
    command: "store"
    aliases: ["shop"]
    permission: ""
    message: "%rc_prefix%&#00ff9cStore &7• &fVisit our store: &#00aaffhttps://store.yourserver.com"

  help:
    enabled: true
    command: "help"
    aliases: ["?"]
    permission: ""
    message-list:
      - "%rc_prefix%&#ffd700Available Commands"
      - "&7• &#ffa500/discord &7- &fJoin our Discord community"
      - "&7• &#ffa500/rules &7- &fView server rules"
      - "&7• &#ffa500/store &7- &fVisit our store"
      - "&7• &#ffa500/help &7- &fShow this help message"