name: RexChat
version: '1.0-SNAPSHOT'
main: cc.rexsystems.rexChat.RexChat
api-version: '1.17'
authors: 
  - Alexutzerion5
description: A powerful chat management plugin

commands:
  rexchat:
    description: Main plugin command
    aliases: [rc]
    permission: rexchat.admin
  clearchat:
    description: Clears the chat
    aliases: [cc]
    permission: rexchat.clear
  mutechat:
    description: Toggles chat mute
    aliases: [mc]
    permission: rexchat.mute
  discord:
    description: Shows Discord information
    aliases: [dc]
  store:
    description: Shows store information
    aliases: [shop]
  rules:
    description: Shows server rules
    aliases: [rule]
  help:
    description: Shows help information
    aliases: [?]

permissions:
  rexchat.admin:
    description: Allows access to admin commands
    default: op
  rexchat.clear:
    description: Allows clearing the chat
    default: op
  rexchat.mute:
    description: Allows muting the chat
    default: op
  rexchat.bypass:
    description: Allows bypassing chat mute
    default: op
